# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 22:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_request_id', models.CharField(db_index=True, max_length=254, unique=True)),
                ('status_notes', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('service_code', models.TextField(null=True)),
                ('service_name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('agency_responsible', models.TextField(null=True)),
                ('service_notice', models.TextField(null=True)),
                ('requested_datetime', models.DateTimeField(null=True)),
                ('updated_datetime', models.DateTimeField(null=True)),
                ('expected_datetime', models.DateTimeField(null=True)),
                ('address_string', models.TextField(null=True)),
                ('media_url', models.TextField(null=True)),
                ('api_key', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('service_object_id', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('service_object_type', models.TextField(null=True)),
                ('detailed_status', models.TextField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='MediaURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.TextField(null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_urls', to='api.Feedback')),
            ],
            options={
                'db_table': 'media_urls',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.TextField(null=True)),
                ('task_type', models.TextField(null=True)),
                ('owner_name', models.TextField(null=True)),
                ('task_modified', models.DateTimeField(null=True)),
                ('task_created', models.DateTimeField(null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Feedback')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
