# Generated by Django 1.9.2 on 2016-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='moderation',
            field=models.CharField(choices=[('unmoderated', 'unmoderated'), ('public', 'public'), ('hidden', 'hidden')], db_index=True, default='public', editable=False, max_length=16),
        ),
    ]
