# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20160221_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='vote_counter',
            field=models.IntegerField(default=0),
        ),
    ]
