# Generated by Django 1.9.2 on 2016-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_service_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_req',
            field=models.CharField(choices=[('coords_or_address', 'require coordinates or address'), ('coords', 'require coordinates (no address)'), ('none', 'require no location')], default='coords_or_address', max_length=32, verbose_name='location requirement'),
        ),
    ]
