# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 07:47
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Model


def recache_lat_long(apps, schema_editor):
    from issues.models import Issue  # This _should_ use apps, but those Issues have no `cache_location`...
    for issue in Issue.objects.filter(location__isnull=False):
        issue._cache_location()
        Model.save(self=issue, update_fields=('lat', 'long'))


class Migration(migrations.Migration):
    dependencies = [
        ('issues', '0004_location_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='lat',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='long',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(
            recache_lat_long,
            reverse_code=migrations.RunPython.noop,
        )
    ]
