# Generated by Django 1.9.6 on 2016-06-14 07:08

from django.db import migrations, models
import django.db.models.deletion
import issues.models.applications


def create_default_application(apps, schema_editor):
    Application = apps.get_model('issues', 'Application')
    obj = Application.objects.create(**issues.models.applications.DEFAULT_APP_DATA)
    assert obj.pk == 1, 'default application PK is not 1, the migration will fail'


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_geo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('identifier', models.CharField(db_index=True, help_text='a machine-readable name for this app (a package identifier, for instance)', max_length=64)),
                ('name', models.CharField(help_text='a human-readable name for this app', max_length=64)),
                ('key', models.CharField(default=issues.models.applications.generate_api_key, editable=False, max_length=32, unique=True)),
            ],
        ),
        migrations.RunPython(create_default_application, migrations.RunPython.noop),
        migrations.AddField(
            model_name='issue',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='issues.Application'),
            preserve_default=False,
        ),
    ]
