# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_mediafile_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
