# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_mediafile_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
