language: python
python: 3.4
addons:
  postgresql: "9.4"
sudo: false
env: DEBUG=1
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
- rm -fr $HOME/.cache/pip/log
install:
- pip install --upgrade pip
- pip install coveralls -r requirements.txt -r requirements-dev.txt
script: py.test .
after_success: coveralls
