# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0002_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.TextField(blank=True)),
                ('task_type', models.TextField(blank=True)),
                ('owner_name', models.TextField(blank=True)),
                ('task_modified', models.DateTimeField(null=True)),
                ('task_created', models.DateTimeField(db_index=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='issues.Issue')),
            ],
            options={
                'ordering': ('task_created',),
            },
        ),
    ]
