# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_vote_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='requested_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
