# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedback_synchronized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.IntegerField()),
                ('service_name', models.TextField()),
                ('description', models.TextField()),
                ('metadata', models.BooleanField()),
                ('type', models.TextField()),
                ('keywords', models.TextField()),
                ('group', models.TextField()),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
