# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 20:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FormFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='parent_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                    to='api.FormFiles'),
        ),
    ]
