# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160309_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.Feedback'),
        ),
    ]
