# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 10:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mediafile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
