# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160408_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='service_code',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
